Repository OpenVisualCloud/SVT-VP9, pull requests merged in 2019-09, with the labels that each got.

#47 MinGW: Change some of the _MSC_VER to _WIN32
  Source/App/EbAppConfig.h
  Source/App/EbAppFifo.c
  Source/App/EbAppMain.c
  Source/Lib/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX512.c
  Source/Lib/ASM_AVX2/quantize_avx.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbThreads.h
  Source/Lib/VPX/bitops.h
  Source/Lib/VPX/tools_common.h
Labels: Clean up

#43 travis: Port changes from SVT-AV1
  .travis.yml
Labels: ci

#59 StaticLib: Add static library support
  .travis.yml
  Build/linux/build.sh
  CMakeLists.txt
  README.md
  Source/API/EbExport_List
  Source/API/EbSvtVp9Time.h
  Source/App/EbAppConfig.h
  Source/App/EbAppFifo.c
  Source/App/EbTime.c
  Source/Lib/Codec/CMakeLists.txt
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEncHandle.h
  Source/Lib/Codec/EbUtility.c
Labels: build, enhancement

#44 Add VBV support for VP9
  Config/Sample.cfg
  Docs/svt-vp9_encoder_user_guide.md
  Source/API/EbSvtVp9Enc.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEncodeContext.c
  Source/Lib/Codec/EbEncodeContext.h
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPacketizationReorderQueue.h
  Source/Lib/Codec/EbRateControlProcess.c
Labels: enhancement
