Repository OpenVisualCloud/SVT-VP9, pull requests merged in 2020-02, with the labels that each got.

#86 ffmpeg-v4.2: Work around the "Too many invisible frames" issue for mp4
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Labels: bug

#87 Only run test with ffmpeg 4.2
  appveyor.yml
Labels: ci

#88 Add OVC Dockerfiles link
  README.md
Labels: documentation

#90 ffmpeg-v4.2: Work around the "Dash-player does not play back..." (#89)
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Labels: bug
