Repository OpenVisualCloud/SVT-VP9, pull requests merged in 2020-05, with the labels that each got.

#104 ffmpeg: Rebase combination patch with SVT-AV1 changes
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
Labels: Clean up

#98 Removing -irefresh-type option from VP9 encoder
  Config/Sample.cfg
  Docs/svt-vp9_encoder_user_guide.md
  Source/API/EbSvtVp9Enc.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEncodeContext.c
  Source/Lib/Codec/EbEncodeContext.h
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
  ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
  gstreamer-plugin/gstsvtvp9enc.c
Labels: Clean up, bug

#107 EbThreads: use lowercase windows.h for case sensitive systems
  Source/Lib/Codec/EbThreads.h
Labels: Clean up

#109 ffmpeg: Add patches for master and n4.2.3 branch
  ffmpeg_plugin/README.md
  ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
  ffmpeg_plugin/master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
  ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9-with-hevc-av1.patch
  ffmpeg_plugin/n4.2.3-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
Labels: ffmpeg
