Repository OpenVisualCloud/SVT-VP9, pull requests merged in 2020-04, with the labels that each got.

#100 CI: Use ffmpeg tags to fix ffmpeg compilation
  .travis.yml
  appveyor.yml
Labels: ci

#99 pkg-config: use CMAKE_INSTALL_FULL for ${prefix}
  Source/Lib/pkg-config.pc.in
Labels: build

#101 appveyor: Disable artifact release for now
  appveyor.yml
Labels: ci

#102 App/EbAppContext.c: Remove unused stream_buffer_pool and allocate_output_buffers
  Source/App/EbAppContext.c
  Source/App/EbAppContext.h
Labels: Clean up
